# Generated by Django 4.0.5 on 2023-04-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_first_name', models.CharField(max_length=50)),
                ('vchr_last_name', models.CharField(max_length=50)),
                ('vchr_user_name', models.CharField(max_length=50, unique=True)),
                ('vchr_email', models.CharField(max_length=50, unique=True)),
                ('bln_activated_email', models.BooleanField(default=False)),
                ('vchr_password_hash', models.CharField(max_length=50)),
                ('vchr_user_type', models.CharField(max_length=50)),
                ('vchr_role', models.CharField(max_length=50)),
                ('int_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
