# Generated by Django 4.0.5 on 2023-04-17 09:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_action_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('fk_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=20)),
                ('int_status', models.IntegerField(default=0)),
                ('arr_assigned', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('fk_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('fk_responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_fk_responsible_id', to='user.user')),
                ('fk_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_updated_by', to='user.user')),
            ],
        ),
    ]
